---

# task file for hadenlabs.php

- name: Update package repositories
  sudo: yes
  apt:
    update_cache: True
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - update_cache

- name: Install php package private dependences
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  register: install_php_private_package_dependences
  with_items: _php_package_dependencies
  when: _php_package_dependencies is defined
  tags:
    - apt
    - dependences

- name: Install php package dependences
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  register: install_php_package_dependences
  with_items: php_package_dependences
  when: php_package_dependences is defined
  tags:
    - apt
    - dependences

- name: Install php dependencies
  sudo: yes
  apt:
    name: "{{ item.name }}"
    state: present
  register: install_php_dependencies
  when: php_dependencies is defined
  with_items: php_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_php_dependencies.stdout_lines