---
# task for hadenlabs.php

- include: install.d/CentOS.yaml
  when: ansible_distribution == "CentOS"
  tags: php

- include: install.d/Ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  tags: php
