---
# task for hadenlabs.php

- name: Install php modules by default
  apt: name={{ item }} state=present update_cache=yes
  with_items: _php_modules_defaults
  when: _php_modules_defaults is defined
  tags:
    - php

- name: Install php modules
  apt: name={{ item }} state=present update_cache=yes
  with_items: php_modules
  when: php_modules is defined
  tags:
    - php