---
# task for hadenlabs.php

- name: Install php modules by default
  apt: name="{{ item }}" state=present update_cache=yes
  with_items: _php_modules_defaults
  when: _php_modules_defaults is defined
  tags:
    - php

- name: Install php modules
  apt: name={{ item }} state=present update_cache=yes
  with_items: php_modules
  when: php_modules is defined
  tags:
    - php

- name: Install PECL libaries.
  command: "pecl install {{ item }}"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  with_items: php_pecl_extensions
  when: php_pecl_extensions is defined
