---

# task file for hadenlabs.php

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes

- name: add package repositories
  apt_repository: repo={{ item }}
  with_items: _php_repositories_packages
  when: _php_repositories_packages

- name: Install version php
  apt: name="{{ _php }}" state=present update_cache=yes
  tags:
    - php

- name: Install php dependences
  apt: name="{{ _php }}-{{ item }}" state=present update_cache=yes
  with_items: _php_packages
  tags:
    - php
